config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "users#index"
  get "/users/new", to: "users#new", as: "new_user"
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  get '/login', to: "sessions#new"
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: "sessions#create"

  get '/libraries', to: 'libraries#index'
  get '/libraries/new', to: 'libraries#new', as: 'new_library'
  post '/libraries', to: 'libraries#create'
  get '/libraries/:library_id', to: 'libraries#show', as: 'library'
  post '/libraries/:library_id/users', to: 'library_users#create', as: 'library_users'


  get '/users/:user_id/libraries', to: 'library_users#index', as: 'user_libraries'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :library_users, dependent: :destroy
  has_many :users, through: :library_users
end

app/models/library_user.rb
class LibraryUser < ApplicationRecord
  belongs_to :user
  belongs_to :library
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, confirmation: true

  has_many :library_users, dependent: :destroy
  has_many :libraries, through: :library_users

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def index
     @libraries = Library.all
  end

  def new
    @library = Library.new
  end

  def create
    @library = Library.create(library_params)
    redirect_to libraries_path  # very light on the error handling, for now!
  end

  def show
    @library = Library.find_by_id(params[:library_id])

  end

  private

  def library_params
    params.require(:library).permit(:name, :floor_count, :floor_area)
  end
end

app/controllers/library_users_controller.rb
class LibraryUsersController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @libraries = @user.libraries # so we type less in the view
  end

  def create
    @library = Library.find(params[:library_id])
    @library.users.push(current_user)  # no error handling currently

    redirect_to current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new

  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    # confirm that email/password combination is correct
    @user = User.confirm(user_params)

    if @user
       login(@user)
       flash[:notice] = "Successfully logged in."      # <--- Add this flash notice
       redirect_to @user
    else
       flash[:error] = "Incorrect email or password."  # <--- Add this flash error
       redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out."        # <--- Add this flash notice
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new

  end

  def create
    @user = User.create(user_params)
    login(@user) # <-- log the user in
    redirect_to @user # <-- go to show
  end

  def show
    @user = User.find_by_id(params[:id])
    render :show

  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/library_users_helper.rb
module LibraryUsersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end
  def require_login
    if current_user.nil?
      flash[:notice] = "Please login first."      # <--- Add this flash notice
      redirect_to "/login"
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logout
    @current_user = session[:user_id] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyLibraryApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
     <% if current_user %>
       <li><%= link_to "Profile", user_path(current_user) %></li>
       <li><%= link_to "Log Out", logout_path %></li>
     <% else %>
       <li><%= link_to "Create Account", new_user_path %></li>
       <li><%= link_to "Log In", login_path %></li>
     <% end %>
   </ul>
   <% flash.each do |name, msg| %>
    <p>
    <small> <%= name.capitalize %>: <%= msg %> </small>
    </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/libraries/index.html.erb
<% @libraries.each do |library| %>
  <div>
    <h3><%= library.name %></h3>
    <% if current_user %>
      <%= button_to "Join", library_users_path(library) %>
    <% end %>
  </div>
  <br>
<% end %>

app/views/libraries/new.html.erb
<%= form_for @library do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= f.number_field :floor_count, placeholder: "Floor Count" %>
  </div>
  <div>
    <%= f.number_field :floor_area, placeholder: "Floor Area" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/libraries/show.html.erb
  Welcome to the <%= @library.name %> <br></br>

  There are <%= @library.floor_count %> floors covering an area of <%= @library.floor_area %> feet!

app/views/library_users/index.html.erb
<div><%= @user.first_name %> is a member of the following libraries</div>

<ul>
  <% @libraries.each do |lib| %>
    <li><%= lib.name %></li>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1>Welcome to Users Index.</h1>

<div>
  There are currently <%= @users.length %> user(s) signed up!
</div>

app/views/users/new.html.erb
Sign Up

<%= form_for @user do |f| %>
  <div>
    <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
    <%= f.email_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<div>
  Welcome, <%= @user.first_name %>!
</div>